Feature/reset password
Goxless/MKTplc pull request #2
Opened 2023-09-17 19:35 UTC by Goxless

Folders rearrange, reset password and refresh actual token functions performed, some refactoringh added

2023-09-22 15:27 UTC, pvoloshin requested changes

2023-09-22 15:27 UTC, pvoloshin commented on src/libs/nodemailer/index.ts
> +const { SMTP_HOST, SMTP_PORT, MAILER_USER, MAILER_PASS } = process.env;
это тоже можно в общий конфиг вынести, весь env выносится в конфиг и в конфиге делается проверка есть ли значения, чтобы убедиться что все будет работать так как надо

P.S. пример такого конфига я тебе скидывал в том репозитории

2023-09-22 15:27 UTC, pvoloshin commented on src/libs/utils/tokens.ts
> +export const generateRefreshToken = (
а зачем нам отдельно рефреш или аксес создавать? они же всегда парой тусят

2023-09-22 15:27 UTC, pvoloshin commented on src/libs/utils/userExist.ts
> +export const userExist = async (checkExistence: boolean, email: string): Promise<any> => {
много где видел Promise<any>
раз уж решил на тайпскрипте то посмотри как из призмы доставать типы

2023-09-22 15:27 UTC, pvoloshin commented on src/libs/utils/userExist.ts
> +    const userDB = await prisma.user.findUnique({
а можно и просто user назвать

2023-09-22 15:27 UTC, pvoloshin commented on src/libs/validationSchemas/authModule/forgetSchema.ts
> +export default forgetSchema;
именные импорты удобнее, меньше шансов что кто то переназовет их что их потом не найти будет

2023-09-22 15:27 UTC, pvoloshin commented on src/libs/validationSchemas/authModule/resetSchema.ts
> +export default forgetSchema;
тоже именной экспорт можно сделать

2023-09-22 15:27 UTC, pvoloshin commented on src/middlewares/authMiddleware.ts
> -import { Context, Next } from 'koa';
в папке middlewares не обязательно надзывать {name}Middlewares, думаю и так понятно будет

2023-09-22 15:27 UTC, pvoloshin commented on src/modules/auth/handlers/logout.ts
> +    const userDB = await userExist(false, email);
можно просто user

2023-09-22 15:27 UTC, pvoloshin commented on src/modules/auth/handlers/refresh.ts
> +    const { id, email } = await userExist(false, token.email);
здорово вынес, нраится

2023-09-22 15:27 UTC, pvoloshin commented on src/modules/auth/handlers/reset.ts
> +    const userId = await redisClient.get(linkId);
а если просто id называть то красивый where будет)

2023-09-22 15:27 UTC, pvoloshin commented on src/modules/auth/handlers/reset.ts
> +    const userId = await redisClient.get(linkId);
а если просто id называть то красивый where будет)

2023-09-22 15:27 UTC, pvoloshin commented on src/modules/auth/handlers/signIn.ts
> +    const user = await userExist(false, email);
тут ты используешь только id, pass, email
можно написать const { id, email, pass } 
будет почище

2023-09-22 15:27 UTC, voloshinp commented on docker-compose.yml
> +    myLittlePostgres:
лучше назвать просто portgres, также почитай доку prisma где сказано что необходима shadow database для правильных миграций, после чего почитай как создать 2 бд в одном постресе

2023-09-22 15:27 UTC, voloshinp commented on src/libs/interfaces/body.ts
> +    id?:string,
???

2023-09-22 15:27 UTC, voloshinp commented on src/modules/auth/index.ts
> +import { verifyAuthorization } from '@/middlewares/authMiddleware';
перед этим можно добавить `/** @module middlewares */`

2023-09-22 15:27 UTC, voloshinp commented on src/utils/httpError.ts
> +export class httpError extends Error {
Классы вроде с большой буквы называются в JS

2023-09-22 15:27 UTC, voloshinp commented on src/utils/httpError.ts
> +    status: number = 500;
зачем задавать по дефолту 500?

2023-09-22 15:27 UTC, voloshinp commented on src/utils/httpError.ts
> +    status: number = 500;
К тому же у тебя в конструкторе обязательное поле статуса, поэтому не нужно задавать сразу 500 код

2023-09-22 15:27 UTC, voloshinp commented on src/utils/prismaClient.ts
> +export default new PrismaClient();
а было хорошо, просто просто написать `export const prisma = new PrismaClient()`

2023-09-24 19:27 UTC, Goxless commented on src/libs/nodemailer/index.ts
> +const { SMTP_HOST, SMTP_PORT, MAILER_USER, MAILER_PASS } = process.env;
А каким образом ты хочешь сделать проверку внутри конфига? Надеюсь, не при постоянном вызове переменных из него? В общем, до конца не понял твою задумку ... 

Плюс не нашел пример конфига, на который ты ссылаешься

2023-09-24 19:27 UTC, Goxless commented on src/libs/utils/tokens.ts
> +export const generateRefreshToken = (
За компанию сделал, по принципу "а вдруг пригодится"

2023-09-24 19:28 UTC, Goxless commented on src/libs/utils/userExist.ts
> +export const userExist = async (checkExistence: boolean, email: string): Promise<any> => {
Из призмы типы достать тяжко, сделал кастомный тип под модель User

2023-09-24 19:29 UTC, Goxless commented on src/libs/validationSchemas/authModule/forgetSchema.ts
> +export default forgetSchema;
Понял. Учту

2023-09-24 19:30 UTC, Goxless commented on src/modules/auth/handlers/reset.ts
> +    const userId = await redisClient.get(linkId);
Думаю, имеет смысл оставить, так как можно перепутать с обьектом user. А так сразу понятно, что переменная имеет прямое отношение к ссылке

2023-09-24 19:30 UTC, Goxless commented on src/modules/auth/handlers/signIn.ts
> +    const user = await userExist(false, email);
Согласен, будет красивее. Но в таком случае получится конфликт тела запроса с обьектом user из бд, так как там одинаковые поля. Есть вариант переименовать поля непосредственно при деструктуризации, но будет ли это иметь смысл? Как по мне - нет

2023-09-24 19:31 UTC, Goxless commented on src/libs/interfaces/body.ts
> +    id?:string,
IReqUserBody - название для интерфейса. А тут у меня тип, так что имеет смысл переименовать, дабы избежать путаницы при использовании

2023-09-24 19:32 UTC, Goxless commented on src/modules/auth/index.ts
> +import { verifyAuthorization } from '@/middlewares/authMiddleware';
Согласен. Исправил

2023-09-24 19:32 UTC, Goxless commented on src/utils/httpError.ts
> +export class httpError extends Error {
Упустил из виду. Уже исправлено

2023-09-28 05:07 UTC, voloshinp commented on src/libs/nodemailer/index.ts
> +const { SMTP_HOST, SMTP_PORT, MAILER_USER, MAILER_PASS } = process.env;
![Screenshot_28-09-2023_08-06@2x](https://github.com/Goxless/MKTplc/assets/34382774/90536824-17d8-4205-9aa4-0ebd493347f2)
![Screenshot_28-09-2023_08-07@2x](https://github.com/Goxless/MKTplc/assets/34382774/c7d1bdd0-527a-4bce-ba1b-304f2185ffc6)

2023-09-28 05:07 UTC, voloshinp commented on src/libs/utils/tokens.ts
> +export const generateRefreshToken = (
Будем писать что то при необходимости

2023-09-28 05:09 UTC, voloshinp commented on src/libs/interfaces/body.ts
> +    id?:string,
Лучше под каждый запрос иметь свой body interface который рядом, потому что body может в будущем сильно отличаться, и чтобы ты не путался что у тебя есть в объекте а что нет лучше разделять, это никак на runtime не повлияет

2023-12-10 17:00 UTC, merged